name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  premerge:
    name: run premerge code checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: check format
        run: yarn format --check
      - name: typecheck
        run: yarn typecheck
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build
        run: |
          docker buildx build \
            --load \
            --tag vexml:latest \
            --cache-to type=gha,mode=max \
            --cache-from type=gha,mode=max \
            .
      - name: test
        run: yarn test:ci
