name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  premerge:
    name: run premerge code checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: check format
        run: yarn format --check
      - name: typecheck
        run: yarn typecheck
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 'vexml/vexml:latest'
          cache-from: type=gha
          cache-to: type=gha
      - name: test
        run: yarn test:ci
